### PR TITLE
Add a link to try the game in a code playground.

### PR DESCRIPTION
**Pull request by dthree**

### CODE REVIEW

**Comment by yannhodiesne** [comment]
A playground link would would be nice, but I suggest adding one which stays in sync with the current state of the main branch instead of hardcoding the project inside the URL

For example: https://codesandbox.io/s/github/cassiozen/TDungeon

**Comment by cassiozen** [comment]
I'd like to make some changes before pushing a playground link:

- Enabling noErrorTruncation
- Wrap the content of other files in one or two modules for isolation

**Comment by orta** [comment]
If you ship the types as an npm module, you can then import in the TS playground via the name of the npm module which might be easier and far simpler for sharing.

**Comment by cassiozen** [comment]
Working on it! (If @orta comments on your humble, just-fooling-around project, you have to stop everything and do as he says...)

**Pull request merged**
